server:
    port: 8080
app:
    service-principal: HTTP/MYSERVER.LOCALHOST@MYSERVER.LOCALHOST
    keytab-location: file:/Users/RVIJAYAN/krb5/conf/krb5.keytab

logging.level.org.springframework.security: TRACE

server.servlet-path: /